services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madness
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@madness.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    image: node:20-alpine
    working_dir: /usr/src/app
    command: sh -c "npm ci && npm run dev"   # or npm start
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/madness
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    working_dir: /usr/src/app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://backend:4000
    depends_on:
      - backend

volumes:
  pgdata:
  pgadmin-data: