services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madness
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@madness.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    image: node:18-alpine
    command: sh -c "echo 'Backend container running — no code yet' && sleep infinity"
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    command: sh -c "echo 'Frontend container running — no code yet' && sleep infinity"
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  pgadmin-data:
